import type { Metadata } from "next";
import "./globals.css";
import Components from "@/components";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
///https://public-files.gumroad.com/kj7evouu5a2rqw377hhlmo78ujkv
///// team-i image-i unoptimzed hanel
/////
/////
/////
/////
/////
/////
/////
/////

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Components>{children}</Components>
            </body>
        </html>
    );
}
